name: flutter_nordic_dfu
description: This library allows you to do a Device Firmware Update (DFU) of your nrf51 or nrf52 chip from Nordic Semiconductor. Currently, it only works for Android.
version: 3.0.0
homepage: https://github.com/fengqiangboy/flutter-nordic-dfu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  
flutter:
  plugin:
    platforms:
      android:
        package: com.timeyaa.flutter_nordic_dfu
        pluginClass: FlutterNordicDfuPlugin
      ios:
        pluginClass: FlutterNordicDfuPlugin
