name: flutter_nordic_dfu
description: This library allows you to do a Device Firmware Update (DFU) of your nrf51 or nrf52 chip from Nordic Semiconductor. Current ,it only works for Android.
version: 2.4.0
author: fengqiangboy <fengqiangboy@gmail.com>
homepage: https://github.com/fengqiangboy/flutter-nordic-dfu

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.timeyaa.flutternordicdfu
    pluginClass: FlutterNordicDfuPlugin
